# Generated by Django 4.2.7 on 2026-10-05 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auth', '0002_userprofile_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6')], default='V1', max_length=2)),
                ('direct_count', models.PositiveIntegerField(default=0)),
                ('network_count', models.PositiveIntegerField(default=0)),
                ('v2_leader_count', models.PositiveIntegerField(default=0)),
                ('v3_leader_count', models.PositiveIntegerField(default=0)),
                ('v4_leader_count', models.PositiveIntegerField(default=0)),
                ('v5_leader_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_stats', to='api_auth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_event', to='api_auth.userprofile')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_referral_events', to='api_auth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('DIRECT', 'Direct'), ('INDIRECT', 'Indirect')], max_length=10)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='assets.referralevent')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_received', to='api_auth.userprofile')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions_generated', to='api_auth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('entry_type', models.CharField(choices=[('REFERRAL_DIRECT', 'Referral direct'), ('REFERRAL_INDIRECT', 'Referral indirect'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=40)),
                ('balance_after', models.DecimalField(decimal_places=18, max_digits=40)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_ledger', to='api_auth.userprofile')),
                ('referral_commission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='assets.referralcommission')),
            ],
        ),
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_usdt', models.DecimalField(decimal_places=18, default=0, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_balance', to='api_auth.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'commission_type', 'generation'), name='unique_referral_commission'),
        ),
    ]
