# Generated by Django 5.2.16 on 2026-10-07 17:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('BINANCE', 'Binance')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('encrypted_api_key', models.TextField()),
                ('encrypted_api_secret', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('can_trade', models.BooleanField(default=True)),
                ('can_withdraw', models.BooleanField(default=False, editable=False)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=30)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], max_length=20)),
                ('wallet_balance', models.DecimalField(decimal_places=12, max_digits=30)),
                ('available_balance', models.DecimalField(decimal_places=12, max_digits=30)),
                ('locked_balance', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('unrealized_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('snapshot_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='trading.exchangeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=100, unique=True)),
                ('exchange_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(max_length=30)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP_MARKET', 'Stop Market'), ('STOP_LIMIT', 'Stop Limit'), ('TAKE_PROFIT_MARKET', 'Take Profit Market'), ('TAKE_PROFIT_LIMIT', 'Take Profit Limit')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=30)),
                ('price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('average_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('EXPIRED_IN_MATCH', 'Expired in Match')], default='NEW', max_length=30)),
                ('reduce_only', models.BooleanField(default=False)),
                ('post_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_created_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_updated_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.exchangeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_trade_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(max_length=30)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=30)),
                ('price', models.DecimalField(decimal_places=12, max_digits=30)),
                ('quote_quantity', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('commission', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('commission_asset', models.CharField(blank=True, max_length=30, null=True)),
                ('is_maker', models.BooleanField(blank=True, null=True)),
                ('executed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='trading.order')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=30)),
                ('entry_price', models.DecimalField(decimal_places=12, max_digits=30)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('liquidation_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('leverage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('margin_type', models.CharField(blank=True, choices=[('ISOLATED', 'Isolated'), ('CROSS', 'Cross')], max_length=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('realized_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.exchangeaccount')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trading.position'),
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=30)),
                ('implementation_key', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled'], name='trading_str_enabled_a96598_idx'), models.Index(fields=['implementation_key'], name='trading_str_impleme_68620f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], max_length=20)),
                ('symbol', models.CharField(max_length=30)),
                ('timeframe', models.CharField(max_length=20)),
                ('leverage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('margin_type', models.CharField(blank=True, choices=[('ISOLATED', 'Isolated'), ('CROSS', 'Cross')], max_length=20, null=True)),
                ('position_mode', models.CharField(blank=True, choices=[('ONE_WAY', 'One Way'), ('HEDGE', 'Hedge')], max_length=20, null=True)),
                ('risk_per_trade', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('max_daily_loss', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_open_positions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='CREATED', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_bots', to='trading.exchangeaccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='trading.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('market_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures')], max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=30)),
                ('entry_price', models.DecimalField(decimal_places=12, max_digits=30)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('gross_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('fees', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('funding', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('net_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.exchangeaccount')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.position')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='trading.tradingbot')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('REDUCE', 'Reduce'), ('CLOSE', 'Close'), ('STOP_BOT', 'Stop Bot')], max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.exchangeaccount')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='trading.tradingbot')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.tradingbot'),
        ),
        migrations.AddField(
            model_name='order',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.tradingbot'),
        ),
        migrations.CreateModel(
            name='FundingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('asset', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=30)),
                ('funding_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('position_side', models.CharField(blank=True, choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10, null=True)),
                ('exchange_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_payments', to='trading.exchangeaccount')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_payments', to='trading.tradingbot')),
            ],
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='trading.tradingbot')),
            ],
        ),
        migrations.CreateModel(
            name='TradingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='trading.tradingbot')),
                ('exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_events', to='trading.exchangeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('START', 'Start'), ('STOP', 'Stop')], max_length=30)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='trading_aud_user_id_e11895_idx'), models.Index(fields=['resource_type', 'resource_id'], name='trading_aud_resourc_c5f572_idx'), models.Index(fields=['action', 'created_at'], name='trading_aud_action_2e1e39_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exchangeaccount',
            index=models.Index(fields=['user', 'exchange'], name='trading_exc_user_id_49b1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeaccount',
            index=models.Index(fields=['enabled'], name='trading_exc_enabled_ab01de_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['exchange_account', 'asset', 'market_type', 'snapshot_at'], name='trading_acc_exchang_2f6058_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfill',
            index=models.Index(fields=['order', 'executed_at'], name='trading_ord_order_i_16ba37_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfill',
            index=models.Index(fields=['symbol', 'executed_at'], name='trading_ord_symbol_82969b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderfill',
            index=models.Index(fields=['exchange_trade_id'], name='trading_ord_exchang_73e0da_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['user', 'status'], name='trading_tra_user_id_297ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['exchange_account'], name='trading_tra_exchang_db78b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['symbol', 'market_type'], name='trading_tra_symbol_c5f897_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingbot',
            index=models.Index(fields=['enabled'], name='trading_tra_enabled_e7acde_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot', 'status'], name='trading_tra_bot_id_a114c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot', 'closed_at'], name='trading_tra_bot_id_126859_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'closed_at'], name='trading_tra_symbol_26dba5_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market_type', 'closed_at'], name='trading_tra_market__1f7faf_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['bot', 'occurred_at'], name='trading_ris_bot_id_5e5806_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['severity', 'occurred_at'], name='trading_ris_severit_5995fe_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['code', 'occurred_at'], name='trading_ris_code_f349ab_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['bot', 'status'], name='trading_pos_bot_id_173387_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['exchange_account', 'symbol'], name='trading_pos_exchang_c15dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['symbol', 'market_type', 'status'], name='trading_pos_symbol_0adfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['bot', 'status'], name='trading_ord_bot_id_ae8826_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['exchange_account', 'status'], name='trading_ord_exchang_60812d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', 'market_type'], name='trading_ord_symbol_847ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['exchange_order_id'], name='trading_ord_exchang_b68492_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingpayment',
            index=models.Index(fields=['exchange_account', 'occurred_at'], name='trading_fun_exchang_02b2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingpayment',
            index=models.Index(fields=['symbol', 'occurred_at'], name='trading_fun_symbol_ba208c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingpayment',
            index=models.Index(fields=['exchange_transaction_id'], name='trading_fun_exchang_2327ff_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['bot', 'occurred_at'], name='trading_tra_bot_id_025a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='trading_tra_event_t_bbb6be_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingevent',
            index=models.Index(fields=['symbol', 'occurred_at'], name='trading_tra_symbol_dad176_idx'),
        ),
    ]
