# Generated by Django 5.2.16 on 2026-09-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('USDT', 'USDT')], default='USDT', max_length=16)),
                ('network', models.CharField(choices=[('bsc', 'BNB Smart Chain')], default='bsc', max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('fee', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('destination_address', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, db_index=True, default='', max_length=66)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
