# Generated by Django 4.2.7 on 2026-09-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_alter_transaction_options_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='deposits.transaction'),
        ),
    ]
