# Generated by Django 5.2.16 on 2026-09-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('sweep', 'Sweep'), ('gas_topup', 'Gas top-up')], max_length=20),
        ),
    ]
